config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  post 'questions', to: 'questions#create', as: 'new_question'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cloney_question.rb
class CloneyQuestion
  attr_reader :title, :body
  def initialize(params)
    @title = params["title"]
    @body = params["body"]
  end
end

app/models/cloney_user.rb
class CloneyUser
  attr_reader :data, :name, :reputation

  def initialize(data)
    @data = data
  end

  def name
    data["name"]
  end

  def reputation
    data["reputation"]
  end

  def email
    data["email"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = CloneyService.users_by_reputation
    @banned_users = CloneyService.banned_users
    @recent_questions = CloneyService.recent_questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def create
    CloneyService.new.create_question(question_params)
    redirect_to root_path
  end

  private

  def question_params
    params.permit(:title, :category_id, :body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="row">
  <div id="users-by-reputation" class="col s6">
    <ul class="collection with-header">
      <li class="collection-header"><h5>Top 10 Users by Reputation</h5></li>
      <% @users.each do |user| %>
      <li class="collection-item">
      <p>Name: <span class="user-name"><%= user.name %></span></p>
      <p>Email: <span><%= user.email %></span></p>
      <p>Reputation: <span class="user-reputation"><%= user.reputation %></span></p>
      </li>
      <% end %>
    </ul>
  </div>

  <div id="banned-users" class="col s6">
    <ul class="collection with-header">
      <li class="collection-header"><h5>Banned Users</h5></li>
      <% @banned_users.each do |user| %>
      <li class="collection-item">
      <p>Name: <span class="user-name"><%= user.name %></span></p>
      <p>Email: <span><%= user.email %></span></p>
      <p>Reputation: <span class="user-reputation"><%= user.reputation %></span></p>
      </li>
      <% end %>
    </ul>
  </div>

  <div id="recent-questions" class="col s6 right">
    <ul class="collection with-header">
      <li class="collection-header"><h5>Recent Questions</h5></li>
      <% @recent_questions.each do |question| %>
      <li class="collection-item">
      <p>Title: <span class="question-title"><%= question.title %></span></p>
      <p>Body: <span><%= question.body %></span></p>
      </li>
      <div class="divider"></div>
      <% end %>
    </ul>
  </div>

  </div>

  <div id="create-question" class="col m12 s10">
    <div class="card-panel">
      <%= form_tag new_question_path  do %>

        <%= label_tag :title %>
        <%= text_field_tag :title %>

        <%= label_tag :body %>
        <%= text_field_tag :body %>

        <%= label_tag :category_id %>
        <%= text_field_tag :category_id %>

        <%= label_tag :user_id %>
        <%= text_field_tag :user_id %>

        <%= submit_tag "Create Question", class: "btn blue" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneyIslandCompanion</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'materialize' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
    <div class="nav-wrapper purple">
      <a href="#" class="brand-logo center purple">Welcome to the Cloney Island Dashboard</a>
      <!-- <ul id="nav-mobile" class="left hide-on-med-and-down purple">
        <li><a href="sass.html">Sass</a></li>
        <li><a href="badges.html">Components</a></li>
        <li><a href="collapsible.html">JavaScript</a></li>
      </ul> -->
    </div>
  </nav>
    <%= yield %>
  </body>
</html>